### PR TITLE
Exception: VARSTART is not 7

### PR DESCRIPTION
**Pull request by astrofrog**
I did encountered again same problem as another issue. I'm trying to read a structure.

```
In [4]: import idlsave

In [5]: idlsave.__version__
Out[5]: '1.0.0'

In [6]: s  = idlsave.read('CMR31303.cxf')
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-6-01f74964d9e5> in <module>()
----> 1 s  = idlsave.read('CMR31303.cxf')

/afs/ipp/home/m/mcavedon/.local/lib/python2.7/site-packages/idlsave/idlsave.pyc in read(file_name, idict, python_dict, uncompressed_file_name, verbose)
    802     # Loop through records, and add them to the list
    803     while True:
--> 804         r = _read_record(f)
    805         records.append(r)
    806         if 'end' in r:

/afs/ipp/home/m/mcavedon/.local/lib/python2.7/site-packages/idlsave/idlsave.pyc in _read_record(f)
    355         varstart = _read_long(f)
    356         if varstart != 7:
--> 357             raise Exception("VARSTART is not 7")
    358
    359         if rectypedesc['structure']:

Exception: VARSTART is not 7
```

Thanks

### CODE REVIEW

**Comment by astrofrog** [comment]
@mcave - thanks for the file, and sorry for the delay! The code attached to this issue now fixes this. I'll wait to see if the tests pass. I'll also fix the same issue in scipy.io.idl (which is the same as idlsave).

**Comment by astrofrog** [comment]
@mcave - this should now be fixed. Try updating to the latest developer version of idlsave - could you let me know if your files work fine now?

**Comment by cave-git-p** [comment]
It does work! Thank you fow your help

**Comment by astrofrog** [comment]
@mcave - and thanks for your patience!

**Pull request merged**
